### ISSUE TITLE
Critical bug: Python Float Parsing

### ISSUE THREAD

**Issue by pjmagee** [microsoft/kiota-serialization-json-python#331]
### What are you generating using Kiota, clients or plugins?

API Client/SDK

### In what context or format are you using Kiota?

Nuget tool

### Client library/SDK language

Python

### Describe the bug

```python
 def get_float_value(self) -> Optional[float]:
        """Gets the float value of the json node
        Returns:
            float: The integer value of the node
        """
        return self._json_node if isinstance(self._json_node, float) else None
```

When a response from an API, says in the OpenAPI Spec it can be a non whole number (float, number), the Python is only returning a numeric value, when the value itself is a literal float, if the number seems to be whole number, it is returning None.

### Expected behavior

Whole numbers should also be taken into consideration, this seems like quite a big problem! Let's take prices as an example, £3.20 as a float is valid, but £3 is also valid. However, in situations where whole numbers (integers) are returned, the float is not parsed. I would expect float(3) to be returned?

Something like this maybe?

```python
if isinstance(self._json_node, (float, int)):
        return float(self._json_node)
```

Type "help", "copyright", "credits" or "license" for more information.
>>> isinstance(5, float)
False
>>> isinstance(5.0, float)
True
>>>

An OpenAPI Specification can say that an API contains numbers other than whole numbers, but here Python needs to ensure the number is maintained and not lost into a 'None'

### How to reproduce

I think it's happening all the time, based on the functionality implemented for get_float_value

### Open API description file

Partial OpenAPI description:

```yaml
attributes:
          type: object
          properties:
            value:
              type: number
              format: double
              example: 27107.99
              description: 'The value of demand for a specified period, ranging from `periodStartDate` to `periodEndDate`.'
            versionDate:
              type: string
              format: date-time
              minLength: 24
              maxLength: 24
              example: '2023-11-14T21:33:38.000Z'
              description: 'For forecasted values, this date indicates when the forecast was generated. For actual values, this date represents the time when the data was collected.'
```

### Kiota Version

1.16.0

### Debug output

<details><summary>Click to expand log</summary>
```


<log output here>

```
</details>
